### ISSUE TITLE
Not setting apiBase in the interceptor?

### ISSUE THREAD

**Issue by misham** [neroniaky/angular-token#467] opened 2018-08-27 17:37 UTC
## I'm submitting a...

- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior
With the apiBase set, it's not prepending it to the path in HTTP calls.  E.g. if I call `this.http.get('foo').subscribe(...)` I see a call to `http://localhost:4200/foo`.  If specify the full path, e.g. `this.http.get('http://myurl.com/foo')` it works fine.

## Expected behavior
The value of apiBase is prepended to the path in the interceptor.

## What is the motivation / use case for changing the behavior?
This is how this used to work in the previous versions.  If something changed in how this is expected to work, none of the docs have been updated.

## Environment

Angular-Token version: 6.0.2
Angular version: 6.1.1

Bundler
- [x] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

Browser:
- [x] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by misham** [comment] 2018-08-27 17:38
One other update, `sign in` & `sign out` plus all the "built-in" functions around auth work just fine.  Only the interceptor is not working for some reason.

**Comment by arjenbrandenburgh** [comment] 2018-08-27 18:55
The idea of an interceptor isn't to modify where a call is going, but to add the login headers (if applicable). If we would add the apiBase to each and every call, your application wouldn't be able to send data to other servers.

In the old angular-token version (0.2.0) we knew 100% that a call would have to go to the same server, since it was a wrapper around the HttpModule (or HttpClientModule). However, now that's no longer the case, you have to specify yourself where a .get has to be sent to, just like you would normally do.

The reason why `signIn` and `signOut` do work, is because we have to send these calls from within the service and catch the response.

As far as I see, what you're experiencing is intended behaviour.

**Comment by arjenbrandenburgh** [comment] 2018-08-29 09:29
Closing this issue. If you feel this is still a bug or shortcoming, feel free to re-open.

**Closed by arjenbrandenburgh** 2018-08-29 09:29 UTC

**Comment by misham** [comment] 2018-09-01 11:26
The source of confusion for me was that the migration docs didn't say anything about that, so that was rather a surprise to debug this problem.

Also, what's the config `apiBase` used for now?  Is it just for the auth paths?

**Comment by neroniaky** [comment] 2018-09-02 07:04
@misham we definitely need to add this to the docs. Haven't found time yet. Sorry for the confusion!

**Comment by arjenbrandenburgh** [comment] 2018-09-03 09:49
@misham The `apiBase` is indeed for the auth paths, but also as a security measure. The token headers are only added to calls going to the `apiBase` server.
